# log path
LOG_FILE_PATH = "train.log"

# data load
TRAIN_DATASET_PATH = ""

# model
LEARNING_RATE = 1e-3
EPOCHS = 100
TRAIN_BATCH_SIZE = 16

IS_TRAIN_CONTINUE = False
MODEL_LOAD_PATH = ""
MODEL_SAVE_PATH = ""
